### PR TITLE
Upgrade sf 3.0

### PR DESCRIPTION
**Pull request by godrar**

### CODE REVIEW

**Comment by lifo101** [comment]
Thanks for the PR. Your changes would break BC with anyone using Symfony < 3. 

The `setDefaultOptions` and 'configureOptions' methods should both be present for BC.
The `getName` and `getBlockPrefix` should both be present for BC.
You also shouldn't use short array syntax since older versions of Symfony only require php 5.3.

**Comment by godrar** [comment]
I added new commit (Backwards compatibility sf2.6), but I have no idea on earlier versions ("OptionsResolverInterface" from "setDefaultOptions" has been removed).

**Comment by xavismeh** [comment]
@lifo101 why not releasing this version as a major release (ie 3.0.0) so we can break compat ?

**Comment by lifo101** [comment]
I didn't use your PR, but I've updated sy2.8|3.0 support in tag v2.3 da548b6

**Pull request closed without merging**
